### ISSUE TITLE
[PE-D][Tester E] deletemember Bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W10-1/tp#164]
This only occurs in a very specific case. When reader add 2 person per group with the SAME names, when deletemember is called on the second group, the person that is deleted appears on the first group, adding on the the number of people in group 1, which is not supposed to happen.

![image.png](https://raw.githubusercontent.com/senwei01/ped/main/files/da13b500-4f6f-483d-a4a8-82a3aae5ae4b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: senwei01/ped#4

**Comment by Tan-Jin-Waye** [comment]
Resolved by #195
