### ISSUE TITLE
DG bugs

### ISSUE THREAD

**Issue by zylee348** [AY2223S1-CS2103T-W10-1/tp#205]
![image](https://user-images.githubusercontent.com/90611909/199283326-bd589a57-54ee-4927-919e-0ab5b1e1aff5.png)

![image](https://user-images.githubusercontent.com/90611909/199283412-60bd69ff-2042-47ac-ae5b-34b710801b4c.png)

![image](https://user-images.githubusercontent.com/90611909/199283445-677b6fa6-182d-4e36-91e7-7773bb75a9c3.png)

**Comment by Tan-Jin-Waye** [comment]
Addressed by PR #207
